name: Check PR diff size
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-diff-size:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Diff PR with main
        run: git diff --name-only origin/main..HEAD > pr-diff.txt

      - name: Count line changes
        run: |
          while read filename; do
            lines=$(git diff origin/main..HEAD $filename | grep -E '^\+[^+]' | wc -l)
            echo "$filename: $lines"
          done < pr-diff.txt > lines-changed.txt

      - name: Check line changes
        run: |
          lines=$(cat lines-changed.txt | awk -F ":" '{sum += $2} END {print sum}')
          if [[ $lines -gt 30 ]]; then
            echo "Error: PR changes exceed the maximum of 30 lines."
            exit 1
          fi
