name: Pull Request Size Limit

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  size_check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Count changed lines
      run: |
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
        NUM_CHANGED_LINES=$(git diff --shortstat HEAD^ HEAD | awk '{print $4}')
        echo "::set-output name=changed_files::$CHANGED_FILES"
        echo "::set-output name=num_changed_lines::$NUM_CHANGED_LINES"

    - name: Check pull request size
      run: |
        NUM_CHANGED_LINES=${{ steps.size_check.outputs.num_changed_lines }}
        if [ "$NUM_CHANGED_LINES" -gt 30 ]; then
          echo "Error: Pull request exceeds size limit (30 lines changed)."
          exit 1
        fi